
const translations = {
    en: {
        "login-title": "Login",
        "login-subtitle": "this is where our adventure begins",
        "email-label": "Email",
        "email": "Enter your email",
        "password-label": "Password",
        "password": "Enter Your Password",
        "or": "or",
        "loginBtn": "Log in",
        "signup-link": "New gamer? Create your account",
        "signupBtn": "Sign up",
        "signup-title": "Create account",
        "signup-subtitle": "Join the PingPong adventure", 
        "signup-username-label": "Username",
        "signup-username": "Enter your username",
        "signup-email-label": "Email",
        "signup-email": "Enter your email",
        "signup-password-label": "Password",
        "signup-password": "Enter your password",
        "signup-confirmpassword-label": "Confirm Password",
        "signup-password1" : "Confirm your password",
        "toggle-login": "Already have an account? <a>Sign in</a>",
        "edit-username": "Edit Username",
        // "toggle-login": "Already have an account? Sign in",
        "jointrnmt": "Join Tournament",
        "local1": "Local",
        "multiplayer1": "Multiplayer",
        "remote1": "Remote",
        "level": "Level",
        "editprfl": "Edit Profile",
        "editprfl1": "Edit Profile",
        "savechanges": "Save Changes",
        "goback-btn": "Go Back",
        "set2":"Settings",
        "changepass": "Change Password",
        "enable2f": "Enable 2FA",
        "disable2f" : "Disable 2FA",
        "currpass": "Current Password",
        "newpass": "New Password",
        "cfmnewpass": "Confirm New Password",
        "savedata": "Save changes",
        "closedata": "Close",
        "enbl2": "Enable 2FA",
        "qrscan": "Scan this QR code with Google Authenticator (or similar app):",
        "passcode-holder": "Enter the 6-digit code generated by your app",
        "sbmt": "Submit",
        "clse": "Close",
        "disable2f1": "Are you sure you want to disable 2FA? This will reduce the security of your account.",
        "cnrfm": "Confirm",
        "cncl": "Cancel",
        "vrf2": "Verify 2FA",
        "vrfinfo": "Enter the 6-digit code from your authenticator app:",
        "verification-passcode": "Enter the code",
        "vrf-submit": "Submit",
        "cls": "Close",
        "leader": "Leaderboard",
        "lvl": "Level",
        "win": "win rate",
        "lose": "lose rate",
        "gamehis": "Game History",
        "ussr": "User",
        "time": "Time",
        "type": "Type",
        "status": "Status",
        "deletacc": "Delete Account",
        "conf-del": "Are you sure you want to delete your account? This action cannot be undone.",
        "confirm-delete": "Confirm",
        "cancel-delete": "Cancel",
        "frnd": "Friends",
        "friendrqst": "Friend Requests",
        "addfrnd": "Add Friend",
        "myfriend": "My Friends",
        "frndrqst": "Friend Requests",
        "cancel-delete": "Cancel",
        "addfrnd1": "Add Friend",
        "add-friend-submit": "Add Friend",
        "add-friend-close": "Close",
        "myfrnd": "My Friends",
        "level": "Level",
        "addfrnd": "Add Friend",
        "cls1": "Close",
        "opponent": "Opponent",
        "match-date" : "Date",
        "match-type" : "Match Type",
        "match-result" : "Result",
        "match-score" : "Score",
        "matchhis": "Match History",
        "lose": "lose rate",
        "win": "win rate",
        "lvl": "Level",
        "leader": "Leaderboard",
        "trnmtregistr" : "Tournament Registration",
        "tournamentBtn" : "Join Tournament",
        "player1" : "Enter Player 1 username",
        "player2" : "Enter Player 2 username",
        "player3" : "Enter Player 3 username",
        "player4" : "Enter Player 4 username",
        "add-friend-username" : "Enter the username of the friend you want to add",
        "cancel-delete1": "Cancel",

        


    },
    fr: {
        "login-title": "Connexion",
        "login-subtitle": "c'est là ou commence notre aventure",
        "email-label": "Email",
        "email": "Entrez votre email",
        "password-label": "Mot de passe",
        "password": "Entrez votre mot de passe",
        "or": "ou",
        "loginBtn": "Se connecter",
        "signup-link": "Nouveau joueur? Créez votre compte",
        "signup-title": "Créer un compte",
        "signup-subtitle": "Rejoignez l'aventure PingPong",
        "signup-username-label": "Nom d'utilisateur",
        "signup-username": "Entrez votre nom d'utilisateur",
        "signup-email-label": "Email",
        "signup-email": "Entrez votre email",
        "signup-password-label": "Mot de passe",
        "signup-password": "Entrez votre mot de passe",
        "signup-confirmpassword-label": "Confirmer le mot de passe",
        "signup-password1": "Confirmez votre mot de passe",
        "signupBtn": "S'inscrire",
        "toggle-login": "Vous avez déjà un compte? <a>Se connecter</a>",
        "edit-username": "Modifier le nom d'utilisateur",
        // "toggle-login": "Vous avez déjà un compte? Se connecter",
        "jointrnmt": "Rejoindre le tournoi",
        "local1": "Local",
        "multiplayer1": "Multijoueur",
        "remote1": "À distance",
        "level": "Niveau",
        "editprfl": "Modifier le profil",
        "editprfl1": "Modifier le profil",
        "savechanges": "Sauvegarder les modifications",
        "goback-btn": "Retour",
        "set2":"Paramètres",
        "changepass": "Changer le mot de passe",
        "enable2f": "Activer 2FA",
        "disable2f" : "Désactiver 2FA",
        "currpass": "Mot de passe actuel",
        "newpass": "Nouveau mot de passe",
        "cfmnewpass": "Confirmer le nouveau mot de passe",
        "savedata": "Sauvegarder les modifications",
        "closedata": "Fermer",
        "enbl2": "Activer 2FA",
        "qrscan": "Scannez ce code QR avec Google Authenticator (ou une application similaire):",
        "passcode-holder": "Entrez le code à 6 chiffres généré par votre application",
        "sbmt": "Soumettre",
        "clse": "Fermer",
        "disable2f1": "Êtes-vous sûr de vouloir désactiver 2FA? Cela réduira la sécurité de votre compte.",
        "cnrfm": "Confirmer",
        "cncl": "Annuler",
        "vrf2": "Vérifier 2FA",
        "vrfinfo": "Entrez le code à 6 chiffres de votre application d'authentification:",
        "verification-passcode": "Entrez le code",
        "vrf-submit": "Soumettre",
        "cls": "Fermer",
        "leader": "Classement",
        "lvl": "Niveau",
        "win": "taux de victoire",
        "lose": "taux de défaite",
        "gamehis": "Historique des jeux",
        "ussr": "Utilisateur",
        "time": "Temps",
        "type": "Type",
        "status": "Statut",
        "deletacc": "Supprimer le compte",
        "conf-del": "Êtes-vous sûr de vouloir supprimer votre compte? Cette action est irréversible.",
        "confirm-delete": "Confirmer",
        "cancel-delete": "Annuler",
        "frnd": "Amis",
        "friendrqst": "Demandes d'amis",
        "addfrnd": "Ajouter un ami",
        "myfriend": "Mes amis",
        "frndrqst": "Demandes d'amis",
        "cancel-delete": "Annuler",
        "addfrnd1": "Ajouter un ami",
        "add-friend-submit": "Ajouter un ami",
        "add-friend-close": "Fermer",
        "myfrnd": "Mes amis",
        "level": "Niveau",
        "addfrnd": "Ajouter un ami",
        "cls1": "Fermer",
        "opponent": "Adversaire",
        "match-date" : "Date",
        "match-type" : "Type de match",
        "match-result" : "Résultat",
        "match-score" : "Score",
        "matchhis": "Historique des matchs",
        "lose": "taux de défaite",
        "win": "taux de victoire",
        "lvl": "Niveau",
        "leader": "Classement",
        "trnmtregistr" : "Inscription au tournoi",
        "tournamentBtn" : "Rejoindre le tournoi",
        "player1" : "Entrez le nom d'utilisateur du joueur 1",
        "player2" : "Entrez le nom d'utilisateur du joueur 2",
        "player3" : "Entrez le nom d'utilisateur du joueur 3",
        "player4" : "Entrez le nom d'utilisateur du joueur 4",
        "add-friend-username" : "Entrez le nom d'utilisateur de l'ami que vous souhaitez ajouter",
        "cancel-delete1": "Annuler",


    },
    es: {
        "login-title": "Iniciar sesión",
        "login-subtitle": "aquí es donde comienza nuestra aventura",
        "email-label": "Correo electrónico",
        "email": "Ingrese su correo electrónico",
        "password-label": "Contraseña",
        "password": "Ingrese su contraseña",
        "or": "o",
        "loginBtn": "Iniciar sesión",
        "signup-link": "¿Nuevo jugador? Crea tu cuenta",
        "signup-title": "Crear cuenta",
        "signup-subtitle": "Únete a la aventura de PingPong",
        "signup-username-label": "Nombre de usuario",
        "signup-username": "Ingrese su nombre de usuario",
        "signup-email-label": "Correo electrónico",
        "signup-email": "Ingrese su correo electrónico",
        "signup-password-label": "Contraseña",
        "signup-password": "Ingrese su contraseña",
        "signup-confirmpassword-label": "Confirmar contraseña",
        "signup-password1": "Confirme su contraseña",
        "signupBtn": "Regístrate",
        "toggle-login": "¿Ya tienes una cuenta? <a>Iniciar sesión</a>",
        // "toggle-login": "¿Ya tienes una cuenta? Iniciar sesión",
        "jointrnmt": "Unirse al torneo",
        "local1": "Local",
        "multiplayer1": "Multijugador",
        "remote1": "Remoto",
        "edit-username": "Editar nombre de usuario",
        "level": "Nivel",
        "editprfl": "Editar perfil",
        "editprfl1": "Editar perfil",
        "savechanges": "Guardar cambios",
        "goback-btn": "Volver",
        "set2":"Configuraciones",
        "changepass": "Cambiar contraseña",
        "enable2f": "Habilitar 2FA",
        "disable2f" : "Deshabilitar 2FA",
        "currpass": "Contraseña actual",
        "newpass": "Nueva contraseña",
        "cfmnewpass": "Confirmar nueva contraseña",
        "savedata": "Guardar cambios",
        "closedata": "Cerrar",
        "enbl2": "Habilitar 2FA",
        "qrscan": "Escanee este código QR con Google Authenticator (o una aplicación similar):",
        "passcode-holder": "Ingrese el código de 6 dígitos generado por su aplicación",
        "sbmt": "Enviar",
        "clse": "Cerrar",
        "disable2f1": "¿Estás seguro de que deseas deshabilitar 2FA? Esto reducirá la seguridad de tu cuenta.",
        "cnrfm": "Confirmar",
        "cncl": "Cancelar",
        "vrf2": "Verificar 2FA",
        "vrfinfo": "Ingrese el código de 6 dígitos de su aplicación de autenticación:",
        "verification-passcode": "Ingrese el código",
        "vrf-submit": "Enviar",
        "cls": "Cerrar",
        "leader": "Tabla de clasificación",
        "lvl": "Nivel",
        "win": "tasa de victorias",
        "lose": "tasa de derrotas",
        "gamehis": "Historial de juegos",
        "ussr": "Usuario",
        "time": "Hora",
        "type": "Tipo",
        "status": "Estado",
        "deletacc": "Eliminar cuenta",
        "conf-del": "¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer.",
        "confirm-delete": "Confirmar",
        "cancel-delete": "Cancelar",
        "frnd": "Amigos",
        "friendrqst": "Solicitudes de amistad",
        "addfrnd": "Agregar amigo",
        "myfriend": "Mis amigos",
        "frndrqst": "Solicitudes de amistad",
        "cancel-delete": "Cancelar",
        "addfrnd1": "Agregar amigo",
        "add-friend-submit": "Agregar amigo",
        "add-friend-close": "Cerrar",
        "myfrnd": "Mis amigos",
        "level": "Nivel",
        "addfrnd": "Agregar amigo",
        "cls1": "Cerrar",
        "opponent": "Oponente",
        "match-date" : "Fecha",
        "match-type" : "Tipo de partido",
        "match-result" : "Resultado",
        "match-score" : "Puntuación",
        "matchhis": "Historial de partidos",
        "lose": "tasa de derrotas",
        "win": "tasa de victorias",
        "lvl": "Nivel",
        "leader": "Tabla de clasificación",
        "trnmtregistr" : "Registro de torneos",
        "tournamentBtn" : "Unirse al torneo",
        "player1" : "Ingrese el nombre de usuario del jugador 1",
        "player2" : "Ingrese el nombre de usuario del jugador 2",
        "player3" : "Ingrese el nombre de usuario del jugador 3",
        "player4" : "Ingrese el nombre de usuario del jugador 4",
        "add-friend-username" : "Ingrese el nombre de usuario del amigo que desea agregar",
        "cancel-delete1": "Cancelar",

    }
};

const languageSelect = document.getElementById('language-select');
const elementsToTranslate = [
    { id: 'login-title', key: 'login-title' },
    { id: 'login-subtitle', key: 'login-subtitle' },
    { id: 'email-label', key: 'email-label' },
    { id: 'email', key: 'email' },
    { id: 'password-label', key: 'password-label' },
    { id: 'password', key: 'password' },
    { id: 'or', key: 'or' },
    { id: 'loginBtn', key: 'loginBtn' },
    { id: 'signup-link', key: 'signup-link' },
    { id: 'signup-title', key: 'signup-title' },
    { id: 'signup-subtitle', key: 'signup-subtitle' },
    { id: 'signupBtn', key: 'signupBtn' },
    { id: 'signup-username-label', key: 'signup-username-label' },
    { id: 'signup-username', key: 'signup-username' },
    { id: 'signup-email-label', key: 'signup-email-label' },
    { id: 'signup-email', key: 'signup-email' },
    { id: 'signup-password-label', key: 'signup-password-label' },
    { id: 'signup-password', key: 'signup-password' },
    { id: 'signup-confirmpassword-label', key: 'signup-confirmpassword-label' },
    { id: 'signup-password1', key: 'signup-password1' },
    { id: 'signupBtn', key: 'signupBtn' },
    { id: 'toggle-login', key: 'toggle-login' },
    { id: 'jointrnmt', key: 'jointrnmt' },
    { id: 'local1', key: 'local1' },
    { id: 'multiplayer1', key: 'multiplayer1' },
    { id: 'remote1', key: 'remote1' },
    { id: 'level', key: 'level'},
    { id: 'edit-username', key: 'edit-username' },
    { id: 'editprfl', key: 'editprfl' },
    { id: 'editprfl1', key: 'editprfl1' },
    { id: 'savechanges', key: 'savechanges' },
    { id: 'goback-btn', key: 'goback-btn' },
    { id: 'set2', key: 'set2' },
    { id: 'changepass', key: 'changepass' },
    { id: 'enable2f', key: 'enable2f' },
    { id: 'disable2f', key: 'disable2f' },
    { id: 'currpass', key: 'currpass' },
    { id: 'newpass', key: 'newpass' },
    { id: 'cfmnewpass', key: 'cfmnewpass' },
    { id: 'savedata', key: 'savedata' },
    { id: 'closedata', key: 'closedata' },
    { id: 'enbl2', key: 'enbl2' },
    { id: 'qrscan', key: 'qrscan' },
    { id: 'passcode-holder', key: 'passcode-holder' },
    { id: 'sbmt', key: 'sbmt' },
    { id: 'clse', key: 'clse' },
    { id: 'disable2f1', key: 'disable2f1' },
    { id: 'cnrfm', key: 'cnrfm' },
    { id: 'cncl', key: 'cncl' },
    { id: 'vrf2', key: 'vrf2' },
    { id: 'vrfinfo', key: 'vrfinfo' },
    { id: 'verification-passcode', key: 'verification-passcode' },
    { id: 'vrf-submit', key: 'vrf-submit' },
    { id: 'cls', key: 'cls' },
    { id: 'leader', key: 'leader' },
    { id: 'lvl', key: 'lvl' },
    { id: 'win', key: 'win' },
    { id: 'lose', key: 'lose' },
    { id: 'gamehis', key: 'gamehis' },
    { id: 'ussr', key: 'ussr' },
    { id: 'time', key: 'time' },
    { id: 'type', key: 'type' },
    { id: 'status', key: 'status' },
    { id: 'deletacc', key: 'deletacc' },
    { id: 'conf-del', key: 'conf-del' },
    { id: 'confirm-delete', key: 'confirm-delete' },
    { id: 'cancel-delete', key: 'cancel-delete' },
    { id: 'frnd', key: 'frnd' },
    { id: 'friendrqst', key: 'friendrqst' },
    { id: 'addfrnd', key: 'addfrnd' },
    { id: 'myfriend', key: 'myfriend' },
    { id: 'frndrqst', key: 'frndrqst' },
    { id: 'cancel-delete', key: 'cancel-delete' },
    { id: 'addfrnd1', key: 'addfrnd1' },
    { id: 'add-friend-submit', key: 'add-friend-submit' },
    { id: 'add-friend-close', key: 'add-friend-close' },
    { id: 'myfrnd', key: 'myfrnd' },
    { id: 'level', key: 'level' },
    { id: 'addfrnd', key: 'addfrnd' },
    { id: 'cls1', key: 'cls1' },
    { id: 'opponent', key: 'opponent' },
    { id: 'match-date', key: 'match-date' },
    { id: 'match-type', key: 'match-type' },
    { id: 'match-result', key: 'match-result' },
    { id: 'match-score', key: 'match-score' },
    { id: 'matchhis', key: 'matchhis' },
    { id: 'lose', key: 'lose' },
    { id: 'win', key: 'win' },
    { id: 'lvl', key: 'lvl' },
    { id: 'leader', key: 'leader' },
    { id: 'trnmtregistr', key: 'trnmtregistr' },
    { id: 'tournamentBtn', key: 'tournamentBtn' },
    { id: 'player1', key: 'player1' },
    { id: 'player2', key: 'player2' },
    { id: 'player3', key: 'player3' },
    { id: 'player4', key: 'player4' },
    { id: 'add-friend-username', key: 'add-friend-username' },
    { id: 'cancel-delete1', key: 'cancel-delete1' },
];







const attachToggleListeners = () => {
    const signupLink = document.querySelector('#signup-link a');
    const toggleLoginLink = document.querySelector('#toggle-login a');

    if (signupLink) {
        signupLink.addEventListener('click', (event) => {
            event.preventDefault();
            document.getElementById('login-form').style.display = 'none';
            document.getElementById('signup-form').style.display = 'block';
        });
    }

    if (toggleLoginLink) {
        toggleLoginLink.addEventListener('click', (event) => {
            event.preventDefault();
            document.getElementById('signup-form').style.display = 'none';
            document.getElementById('login-form').style.display = 'block';
        });
    }
};


const translatePage = (lang) => {
    elementsToTranslate.forEach(({ id, key }) => {
        const element = document.getElementById(id);

        if (id === 'signup-link') {
            const linkElement = element.querySelector('a');
            element.firstChild.textContent = translations[lang]["signup-link"].split("?")[0] + "? ";
            if (linkElement) {
                linkElement.textContent = translations[lang]["signup-link"].split("?")[1]?.trim();
            }
        } else if (id === "toggle-login") {
            const parentText = translations[lang][key].split("<a>")[0];
            const linkText = translations[lang][key].split("<a>")[1]?.split("</a>")[0] || "";
            const linkElement = element.querySelector("a");

            if (linkElement) {
                element.childNodes[0].textContent = parentText;
                linkElement.textContent = linkText;
            }
        } else if (element) {
            element.textContent = translations[lang][key];
        }
    });


    document.getElementById('email').placeholder = translations[lang]["email"];
    document.getElementById('password').placeholder = translations[lang]["password"];
    document.getElementById('signup-username').placeholder = translations[lang]["signup-username"];
    document.getElementById('signup-email').placeholder = translations[lang]["signup-email"];
    document.getElementById('signup-password').placeholder = translations[lang]["signup-password"];
    document.getElementById('signup-password1').placeholder = translations[lang]["signup-password1"];
    document.getElementById('currpass').placeholder = translations[lang]["currpass"];
    document.getElementById('newpass').placeholder = translations[lang]["newpass"];
    document.getElementById('cfmnewpass').placeholder = translations[lang]["cfmnewpass"];
    document.getElementById('passcode-holder').placeholder = translations[lang]["passcode-holder"];
    document.getElementById('edit-username').placeholder = translations[lang]["edit-username"];
    document.getElementById('verification-passcode').placeholder = translations[lang]["verification-passcode"];
    document.getElementById('player1').placeholder = translations[lang]["player1"];
    document.getElementById('player2').placeholder = translations[lang]["player2"];
    document.getElementById('player3').placeholder = translations[lang]["player3"];
    document.getElementById('player4').placeholder = translations[lang]["player4"];
    document.getElementById('add-friend-username').placeholder = translations[lang]["add-friend-username"];

    
    attachToggleListeners();
};


languageSelect.addEventListener('change', (event) => {
    const selectedLang = event.target.value;
    translatePage(selectedLang);
    localStorage.setItem('selectedLanguage', selectedLang);
});

const storedLanguage = localStorage.getItem('selectedLanguage') || 'en';
languageSelect.value = storedLanguage;
translatePage(storedLanguage);





